name: dp-dev

services:
  ethereum-node:
    container_name: dp-dev-ethereum-node
    build:
      context: ./services/smart-contract
      dockerfile: Dockerfile
    ports:
      - '8545:8545'
    volumes:
      - ./scripts/startup/local-development-setup-data.json:/app/local-development-setup-data.json:ro

  rabbitmq:
    container_name: dp-dev-rabbitmq
    image: rabbitmq:3.13.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-volumes/dev/rabbitmq/data:/var/lib/rabbitmq:rw
      - ./.docker-volumes/dev/rabbitmq/logs:/var/log/rabbitmq:rw
      - ./scripts/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./scripts/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  blockchain-service-postgres:
    container_name: dp-dev-blockchain-service-postgres
    image: postgres:15.4-alpine3.18
    environment:
      PGPORT: ${BLOCKCHAIN_SERVICE_POSTGRES_PORT}
      POSTGRES_DB: ${BLOCKCHAIN_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${BLOCKCHAIN_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BLOCKCHAIN_SERVICE_POSTGRES_PASSWORD}
    ports:
      - '5433:5433'
    volumes:
      - ./.docker-volumes/dev/blockchain-service-postgres:/var/lib/postgresql/data:rw

  delivery-service-postgres:
    container_name: dp-dev-delivery-service-postgres
    image: postgres:15.4-alpine3.18
    environment:
      PGPORT: ${DELIVERY_SERVICE_POSTGRES_PORT}
      POSTGRES_DB: ${DELIVERY_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${DELIVERY_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DELIVERY_SERVICE_POSTGRES_PASSWORD}
    ports:
      - '5434:5434'
    volumes:
      - ./.docker-volumes/dev/delivery-service-postgres:/var/lib/postgresql/data:rw

  mailpit:
    container_name: dp-dev-mailpit
    image: axllent/mailpit:v1.19.1
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - ./.docker-volumes/dev/mailpit:/data:rw

  jaeger:
    container_name: dp-dev-jaeger
    image: jaegertracing/all-in-one:1.60
    ports:
      - '4317:4317'
      - '16686:16686'
