name: blockchain-service-common

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      name: Setup bun
      with:
        bun-version: 1.1.18
    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: services/blockchain-service
