/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Delivery } from "./Delivery";
export * as factories from "./factories";
export { Delivery__factory } from "./factories/Delivery__factory";
