name: delivery-ui-common

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      name: Setup node
      with:
        node-version: 20.12.2
    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      shell: bash
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('services/delivery-ui/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node- # Takes by latest cache key if failed to find by current key
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: services/delivery-ui
