name: blockchain-service

on:
  pull_request:
    branches:
      - '*'
    paths:
      - .github/actions/*/**
      - .github/workflows/**
      - 'services/blockchain-service/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/blockchain-service-common
        name: Setup blockchain service
      - name: Lint
        run: bun run lint
        working-directory: services/blockchain-service
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/blockchain-service-common
        name: Setup blockchain service
      - name: Unit Test
        run: bun run test --env-file=.env.test
        working-directory: services/blockchain-service
