name: smart-contract

on:
  pull_request:
    branches:
      - '*'
    paths:
      - .github/actions/*/**
      - .github/workflows/**
      - 'services/smart-contract/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/smart-contract-common
        name: Setup smart contract
      - name: Build
        run: npm run build
        working-directory: services/smart-contract
        env:
          NODE_ENV: test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/smart-contract-common
        name: Setup smart contract
      - name: Lint
        run: npm run lint
        working-directory: services/smart-contract
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/smart-contract-common
        name: Setup smart contract
      - name: Unit Test
        run: npm run test
        working-directory: services/smart-contract
