name: tracking-ui

on:
  pull_request:
    branches:
      - '*'
    paths:
      - .github/actions/*/**
      - .github/workflows/**
      - 'services/tracking-ui/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/tracking-ui-common
        name: Setup tracking ui
      - name: Build
        run: npm run build
        working-directory: services/tracking-ui
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/tracking-ui-common
        name: Setup tracking ui
      - name: Lint
        run: npm run lint
        working-directory: services/tracking-ui
